version: "3"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=*******
      - POSTGRES_PASSWORD=*******
      - POSTGRES_DB=CarSystem
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      - DB_USER=*******
      - DB_PASSWORD=*******
      - DB_URL=jdbc:postgresql://db:5432/CarSystem
    ports:
      - "8080:8080"
    depends_on:
      - db
